categories/urls.py
from django.urls import path

from . import views

app_name = "categories"

urlpatterns = [
    # ex: /categories/create/
    path(
        "create/",
        views.CategoryCreateView.as_view(),
        name="create"
    ),
    # ex: /categories/all/
    path(
        "all/",
        views.CategoriesReadView.as_view(),
        name="all"
    ),
    # ex: /categories/update/13
    path(
        "update/<int:pk>",
        views.CategoryUpdateView.as_view(),
        name="update"
    ),
    # ex: /categories/delete/13
    path(
        "delete/<int:pk>",
        views.CategoryDeleteView.as_view(),
        name="delete"
    ),
    # ex: /categories/detail/12
    path(
        "detail/<int:pk>",
        views.CategoryDetailView.as_view(),
        name="detail"
    )
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "common"
urlpatterns = [
    # ex: /
    path("", views.home_view, name="home"),
]

products/urls.py
from django.urls import path

from . import views

app_name = "products"

urlpatterns = [
    # ex: /products/create/
    path(
        "create/",
        views.ProductCreateView.as_view(),
        name="create"
    ),
    # ex: /products/all/
    path(
        "all/",
        views.ProductsReadView.as_view(),
        name="all"
    ),
    # ex: /products/update/12
    path(
        "update/<int:pk>",
        views.ProductUpdateView.as_view(),
        name="update"
    ),
    # ex: /products/delete/12
    path(
        "delete/<int:pk>",
        views.ProductDeleteView.as_view(),
        name="delete"
    ),
    # ex: /products/datail/12
    path(
        "detail/<int:pk>",
        views.ProductDetailView.as_view(),
        name="detail"
    ),
    # ex: /products/counter_sales/
    path(
        "counter_sales/",
        views.counter_sales_view,
        name="counter_sales"
    ),
]

store_administration/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('categories/', include('categories.urls')),
    path('products/', include('products.urls')),
]

categories/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    """ Categories for each product of the store """

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    name = models.CharField(max_length=50)
    description = models.TextField(max_length=200)
    sales = models.IntegerField(default=0)

    def get_products(self):
        return self.product_set.all()

    def __str__(self):
        return self.name
    

products/models.py
import datetime

from django.db import models
from django.utils import timezone

from categories.models import Category

# Create your models here.

class Product(models.Model):
    """ Porducts of the store """

    class Meta:
        verbose_name = "Product"
        verbose_name_plural = "Products"

    name = models.CharField(max_length=50)
    description = models.TextField(max_length=200)
    price = models.IntegerField()
    pub_date = models.DateField(default=timezone.now)
    sales = models.IntegerField(default=0)
    available = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def counter_sales(self):
        self.sales += 1
        category = self.category
        category.sales += 1 
        category.save()
        self.available -= 1
        
        if self.available <= 0:
            is_available = False

        self.save()

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def __str__(self):
        return self.name
    

categories/forms.py
from django.forms import ModelForm

from . import models

class CategoryForm(ModelForm):

    class Meta:
        model = models.Category
        fields = ('name', 'description',)
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

products/forms.py
from django.forms import ModelForm

from . import models

class ProductForm(ModelForm):
    class Meta:
        model = models.Product
        fields = (
            'name',
            'description',
            'price',
            'available',
            'category',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
    

categories/views.py
from django.views import generic
from django.urls import reverse_lazy

from . import models
from . import forms

class CategoriesViews():
    """
    Parent generic view to avoid repeating
    the line indicating the view pattern.
    """

    model = models.Category

class CategoriesCUViews(CategoriesViews):
    """
    Parent generic view for the views responsible
    for creating and updating categories.
    """
    
    form_class = forms.CategoryForm
    success_url = reverse_lazy("categories:all")

# Create your views here.

class CategoryCreateView(CategoriesCUViews, generic.CreateView):
    template_name = "categories/create.html"

class CategoriesReadView(CategoriesViews, generic.ListView):
    template_name = "categories/read.html"
    context_object_name = "categories"

class CategoryUpdateView(CategoriesCUViews, generic.UpdateView):
    template_name = "categories/update.html"
    context_object_name = "category"

class CategoryDeleteView(CategoriesViews, generic.DeleteView):
    success_url = reverse_lazy("categories:all")

class CategoryDetailView(CategoriesViews, generic.DetailView):
    template_name = "categories/detail.html"
    context_object_name = "category"

common/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse

from categories import models as models_categories
from products import models as models_products

# Create your views here.

def home_view(request):
    return render(request, 'common/home.html')

products/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.urls import reverse_lazy

from . import models
from . import forms

class ProductsViews():
    """
    Parent generic view to avoid repeating
    the line indicating the view pattern.
    """

    model = models.Product

class ProductsCUViews(ProductsViews):
    """
    Parent generic view for the views responsible
    for creating and updating products.
    """

    form_class = forms.ProductForm
    success_url = reverse_lazy("products:all")

# Create your views here.

class ProductCreateView(ProductsCUViews, generic.CreateView):
    template_name = "products/create.html"

class ProductsReadView(ProductsViews, generic.ListView):
    template_name = "products/read.html"
    context_object_name = "products"

class ProductUpdateView(ProductsCUViews, generic.UpdateView):
    template_name = "products/update.html"
    context_object_name = "product"

class ProductDeleteView(ProductsViews, generic.DeleteView):
    success_url = reverse_lazy("products:all")

class ProductDetailView(ProductsViews, generic.DetailView):
    template_name = "products/detail.html"
    context_object_name = "product"

def counter_sales_view(request):
    product = get_object_or_404(models.Product, pk=request.POST['id_product'])

    if 'action' not in request.POST:
        context = {'product': product}
        return render(request, 'products/counter_sales.html', context)

    product.counter_sales()

    return HttpResponseRedirect(reverse('products:all'))

categories/templates/categories/category_confirm_delete.html
{% extends "bases/delete.html" %}
{% block content_title %}Delete category{% endblock content_title %}
{% block question %}Are you sure you want to delete this category?{% endblock question %}
{% block cancel_url %}{% url 'categories:all' %}{% endblock cancel_url %}

categories/templates/categories/create.html
{% extends "bases/form_categories.html" %}
{% block content_title %}New category{% endblock content_title %}

categories/templates/categories/detail.html
{% extends "bases/datatable_categories_detail.html" %}
{% block content_title %}{{ category.name }}{% endblock content_title %}
{% block body %}
{% for product in category.product_set.all %}
<tbody>
    <tr>
        <td>{{ product.name }}</td>
        <td>{{ product.price }}</td>
        <td>{{ product.available }}</td>
        <td>
            {% if product.is_available %}
                <form action="{% url 'products:counter_sales' %}" method="post" class="d-inline">
                    {% csrf_token %}
                    <input type="hidden" name="id_product" value="{{ product.id }}">
                    <button type="submit" class="btn btn-success btn-circle" role="button"><i class="fas fa-dollar-sign"></i></button>
                </form>
            {% endif %}
            <a href="{% url 'products:detail' product.id  %}" class="btn btn-warning btn-circle" role="button"><i class="fas fa-eye"></i></a>
            <a href="{% url 'products:update' product.id %}" class="btn btn-info btn-circle" role="button"><i class="far fa-edit"></i></a>
            <a href="{% url 'products:delete' product.id  %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
        </td>
    </tr>
</tbody>
{% endfor %}
{% endblock body %}

categories/templates/categories/read.html
{% extends "bases/datatable_categories.html" %}
{% block content_title %}Categories{% endblock content_title %}
{% block body %}
{% for category in categories %}
<tbody>
    <tr>
        <td>{{ category.name }}</td>
        <td>{{ category.description }}</td>
        <td>{{ category.sales }}</td>
        <td>
            <a href="{% url 'categories:detail' category.id  %}" class="btn btn-warning btn-circle" role="button"><i class="fas fa-eye"></i></a>
            <a href="{% url 'categories:update' category.id %}" class="btn btn-info btn-circle" role="button"><i class="far fa-edit"></i></a>
            <a href="{% url 'categories:delete' category.id  %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
        </td>
    </tr>
</tbody>
{% endfor %}
{% endblock body %}

categories/templates/categories/update.html
{% extends "bases/form_categories.html" %}
{% block content_title %}Update category{% endblock content_title %}

common/templates/common/home.html
{% extends "bases/base.html" %}
{% block page_content %}
<div class="row">
	<a href="{% url 'categories:create' %}" class="btn btn-primary">New category</a>
	<a href="{% url 'products:create' %}" class="btn btn-info">New product</a>
</div>	
{% endblock page_content %}

products/templates/products/counter_sales.html
{% extends "bases/form.html" %}
{% block content_title %}Counter sales{% endblock content_title %}
{% block page_content %}
<div class="row">
	<div class="col-md-8">
		<div class="card">
			<form action="{% url 'products:counter_sales' %}" method="post">
				{% csrf_token %}
				<div class="card-body">
					<div class="form-groups">
						<label>Do  you want to register the sale of this product?</label>
						<input type="hidden" name="id_product" value="{{ product.id }}">
						<input type="hidden" name="action" value="register_sale">
					</div>
				</div>
				<div class="card-footer">
					<button type="submit" class="btn btn-success">Save</button>
        			<a href="{% url 'products:all' %}" class="btn btn-danger">Cancel</a>
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock page_content %}

products/templates/products/create.html
{% extends "bases/form_products.html" %}
{% block content_title %}New product{% endblock content_title %}

products/templates/products/detail.html
{% extends "bases/datatable_products_detail.html" %}
{% block content_title %}{{ product.name }}{% endblock content_title %}
{% block body %}
<tbody>
    <tr>
        <td>{{ product.name }}</td>
        <td>{{ product.description }}</td>
        <td>{{ product.price }}</td>
        <td>{{ product.sales }}</td>
        <td>{{ product.available }}</td>
        <td>{{ product.category }}</td>
        <td>
            {% if product.is_available %}
                <form action="{% url 'products:counter_sales' %}" method="post" class="d-inline">
                    {% csrf_token %}
                    <input type="hidden" name="id_product" value="{{ product.id }}">
                    <button type="submit" class="btn btn-success btn-circle" role="button"><i class="fas fa-dollar-sign"></i></button>
                </form>
            {% endif %}
            <a href="{% url 'products:detail' product.id  %}" class="btn btn-warning btn-circle" role="button"><i class="fas fa-eye"></i></a>
            <a href="{% url 'products:update' product.id %}" class="btn btn-info btn-circle" role="button"><i class="far fa-edit"></i></a>
            <a href="{% url 'products:delete' product.id  %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
        </td>
    </tr>
</tbody>
{% endblock body %}

products/templates/products/product_confirm_delete.html
{% extends "bases/delete.html" %}
{% block content_title %}Delete product{% endblock content_title %}
{% block question %}Are you sure you want to delete this product?{% endblock question %}
{% block cancel_url %}{% url 'products:all' %}{% endblock cancel_url %}

products/templates/products/read.html
{% extends "bases/datatable_products.html" %}
{% block content_title %}Products{% endblock content_title %}
{% block body %}
{% for product in products %}
<tbody>
    <tr>
        <td>{{ product.name }}</td>
        <td>{{ product.price }}</td>
        <td>{{ product.available }}</td>
        <td>
            {% if product.is_available %}
                <form action="{% url 'products:counter_sales' %}" method="post" class="d-inline">
                    {% csrf_token %}
                    <input type="hidden" name="id_product" value="{{ product.id }}">
                    <button type="submit" class="btn btn-success btn-circle" role="button"><i class="fas fa-dollar-sign"></i></button>
                </form>
            {% endif %}
            <a href="{% url 'products:detail' product.id  %}" class="btn btn-warning btn-circle" role="button"><i class="fas fa-eye"></i></a>
            <a href="{% url 'products:update' product.id %}" class="btn btn-info btn-circle" role="button"><i class="far fa-edit"></i></a>
            <a href="{% url 'products:delete' product.id  %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
        </td>
    </tr>
</tbody>
{% endfor %}
{% endblock body %}

products/templates/products/update.html
{% extends "bases/form_products.html" %}
{% block content_title %}Update product{% endblock content_title %}

templates/bases/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Store purchase management system. ">
    <meta name="author" content="Deibys">

    <title>{% block page_title %}Store Administration{% endblock page_title %}</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'bases/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'bases/css/main.min.css' %}" rel="stylesheet">

    {% block css %}{% endblock css %}

</head>
<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Store Admin</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Sales</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Store
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'categories:all' %}" data-toggle="collapse" data-target="#collapseOne"
                    aria-expanded="true" aria-controls="collapseOne">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Categories</span>
                </a>
                <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="{% url 'categories:create' %}">New</a>
                        <a class="collapse-item" href="{% url 'categories:all' %}">See all</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'products:all' %}" data-toggle="collapse" data-target="#collapseTwo"
                    aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Products</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="{% url 'products:create' %}">New</a>
                        <a class="collapse-item" href="{% url 'products:all' %}">See all</a>
                    </div>
                </div>
            </li>

        </ul>
        <!-- End of sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
                    <form
                        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                                aria-label="Search" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="button">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                            placeholder="Search for..." aria-label="Search"
                                            aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>
                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <h1 class="h3 mb-4 text-gray-800">{% block content_title %}Home{% endblock content_title %}</h1>

                    {% block page_content %}
                        
                    {% endblock page_content %}

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Make by Deibys :&#41;</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

<!-- Bootstrap core JavaScript-->
    <script src="{% static 'bases/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'bases/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'bases/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    {% block js %}{% endblock js %}

    <!-- Custom scripts for all pages-->
    <script src="{% static 'bases/js/main.min.js' %}"></script>

</body>

</html>

templates/bases/datatable.html
{% extends "bases/base.html" %}
{% load static %}
{% block css %}
	<link rel="stylesheet" href="{% static 'bases/vendor/datatables/dataTables.bootstrap4.min.css' %}">
{% endblock css %}
{% block page_content %}
<div class="card shadow mb-4">
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                {% block head_footer %}{% endblock head_footer %}
                {% block body %}{% endblock body %}
            </table>
        </div>
    </div>
</div>    
{% endblock page_content %}
{% block js %}
<script src="{% static 'bases/vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'bases/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'bases/js/datatable.js' %}"></script>
{% endblock js %}

templates/bases/datatable_categories.html
{% extends "bases/datatable.html" %}
{% block head_footer %}
<thead>
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Sales</th>
        <th>Actions</th>
    </tr>
</thead>
<tfoot>
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Sales</th>
        <th>Actions</th>
    </tr>
</tfoot>
{% endblock head_footer %}

templates/bases/datatable_categories_detail.html
{% extends "bases/datatable.html" %}
{% block head_footer %}
<thead>
    <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Available</th>
        <th>Actions</th>
    </tr>
</thead>
<tfoot>
    <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Available</th>
        <th>Actions</th>
    </tr>
</tfoot>
{% endblock head_footer %}

templates/bases/datatable_products.html
{% extends "bases/datatable_categories_detail.html" %}

templates/bases/datatable_products_detail.html
{% extends "bases/datatable.html" %}
{% block head_footer %}
<thead>
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
        <th>Sales</th>
        <th>Available</th>
        <th>Category</th>
        <th>Actions</th>
    </tr>
</thead>
<tfoot>
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
        <th>Sales</th>
        <th>Available</th>
        <th>Category</th>
        <th>Actions</th>
    </tr>
</tfoot>
{% endblock head_footer %}

templates/bases/delete.html
{% extends "bases/base.html" %}
{% block page_content %}
<div class="row">
	<div class="col-md-8">
		<div class="card card-danger">
			<form role="form" method="post">
				{% csrf_token %}
				<div class="card-body">
					<div class="form-group">
						<label>{% block question %}{% endblock question %}</label>
					</div>
				</div>
				<div class="card-footer">
					<button type="submit" class="btn btn-success">Delete</button>
					<a href="{% block cancel_url %}{% endblock cancel_url %}" class="btn btn-danger">Cancel</a>
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock page_content %}

templates/bases/form.html
{% extends "bases/base.html" %}
{% block page_content %}
<div class="row">
	<div class="col-md-8">
		<div class="card mb-4">
			<form method="post">
				{% csrf_token %}
				<div class="card-body mb-3">
					{% block form_groups %}
						
					{% endblock form_groups %}
					<div class="form-group">
						<span class="text-danger">
							{% if form.errors %}
								{% for field in form %}
									{% if field.errors %}
										{% for error in field.errors %}
											{{ error|escape }}
										{% endfor %}
									{% endif %}
								{% endfor %}
								{% if form.non_field_errors %}
									{% for error in form.non_field_errors %}
										{{ error|escape }}
									{% endfor %}
								{% endif %}
							{% endif %}
						</span>
					</div>
				</div>
				<div class="card-footer mt-3">
					<button type="submit" class="btn btn-success">Save</button>
        			<a href="{% block cancel_url %}{% endblock cancel_url %}" class="btn btn-danger">Cancel</a>
				</div>
			</form>
		</div>
	</div>
</div>	
{% endblock page_content %}

templates/bases/form_categories.html
{% extends "bases/form.html" %}

{% block form_groups %}
<div class="form-group">
	<label for="id_name">Name</label>
	{{ form.name }}
</div>
<div class="form-group">
	<label for="id_description">Description</label>
	{{ form.description }}
</div>
{% endblock form_groups %}
{% block cancel_url %}{% url 'categories:all' %}{% endblock cancel_url %}

templates/bases/form_products.html
{% extends "bases/form.html" %}

{% block form_groups %}
<div class="form-group">
	<label for="id_name">Name</label>
	{{ form.name }}
</div>
<div class="form-group">
	<label for="id_description">Description</label>
	{{ form.description }}
</div>
<div class="form-group">
	<label for="id_price">Price</label>
	{{ form.price }}
</div>
<div class="form-group">
	<label for="id_available">Available</label>
	{{ form.available }}
</div>
<div class="form-group">
	<label for="id_category">Category</label>
	{{ form.category }}
</div>
{% endblock form_groups %}
{% block cancel_url %}{% url 'products:all' %}{% endblock cancel_url %}